In [72]:
import pandas as pd
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [73]:
df = pd.read_csv('ReviewsEN.csv')

In [74]:
print("-1 :", df['sentiment'].value_counts()[-1])
print("0 :", df['sentiment'].value_counts()[0])
print("1 :", df['sentiment'].value_counts()[1])

-1 : 553
0 : 404
1 : 948


In [75]:
df['sentiment'].unique()

array([ 0,  1, -1])

In [76]:
# Replace values in pandas DataFrame.
df['sentiment'] = df['sentiment'].replace([1], 2)
df['sentiment'] = df['sentiment'].replace([0], 1)
df['sentiment'] = df['sentiment'].replace([-1], 0)

In [77]:
df['reviews'] = df['reviews'].apply(str.lower)
print(df)

      sentiment                                            reviews
0             1  teacher are punctual but they should also give...
1             2                                               good
2             2  excellent lectures are delivered by teachers a...
3             2  teachers give us all the information required ...
4             2                                                yes
...         ...                                                ...
1900          2  the greatest teacher i have ever had. he's bri...
1901          2  the best professor that we have in stcloud sta...
1902          2  highest recommendations. his accent and integr...
1903          2  great teacher, go to class and do hw, you'll d...
1904          2  very good professor, probably the best in the ...

[1905 rows x 2 columns]


# Stopwords

In [78]:
# opening the file in read mode
my_file = open("stopwords.txt", "r")
  
# reading the file
data = my_file.read()
  
# replacing end splitting the text 
# when newline ('\n') is seen.
stopwords_data = data.split("\n")
print(stopwords_data)
my_file.close()

['a', 'about', 'above', 'across', 'after', 'again', 'against', 'all', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'among', 'an', 'and', 'another', 'any', 'anybody', 'anyone', 'anything', 'anywhere', 'are', 'area', 'areas', 'around', 'as', 'ask', 'asked', 'asking', 'asks', 'at', 'away', 'b', 'back', 'backed', 'backing', 'backs', 'be', 'became', 'because', 'become', 'becomes', 'been', 'before', 'began', 'behind', 'being', 'beings', 'best', 'better', 'between', 'big', 'both', 'but', 'by', 'c', 'came', 'can', 'cannot', 'case', 'cases', 'certain', 'certainly', 'clear', 'clearly', 'come', 'could', 'd', 'did', 'differ', 'different', 'differently', 'do', 'does', 'done', 'down', 'down', 'downed', 'downing', 'downs', 'during', 'e', 'each', 'early', 'either', 'end', 'ended', 'ending', 'ends', 'enough', 'even', 'evenly', 'ever', 'every', 'everybody', 'everyone', 'everything', 'everywhere', 'f', 'face', 'faces', 'fact', 'facts', 'far', 'felt', 'few', 'find', 'finds', 'first

In [79]:
import string

def remove_punctuation(text):
    # Remove punctuation marks
    translator = str.maketrans('', '', string.punctuation)
    text_without_punctuation = text.translate(translator)
    return text_without_punctuation

In [80]:
cleaned_text = []
for i in range(len(df)):
  cleaned_text.append(remove_punctuation(df['reviews'][i]))

df['reviews'] = cleaned_text
df['reviews'].values

array(['teacher are punctual but they should also give us the some practical knowledge other than theortical',
       'good',
       'excellent lectures are delivered by teachers and all teachers are very punctual',
       ...,
       'highest recommendations his accent and integrity will keep you awake',
       'great teacher go to class and do hw youll do good',
       'very good professor probably the best in the csci department'],
      dtype=object)

In [81]:
# GRADED FUNCTION: remove_stopwords
def remove_stopwords(sentence, data):
    """
    Removes a list of stopwords
    
    Args:
        sentence (string): sentence to remove the stopwords from
    
    Returns:
        sentence (string): lowercase sentence without the stopwords
    """
    # List of stopwords

    stopwords = data + ["a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", "during", "each", "few", "for", "from", "further", "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its", "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so", "some", "such", "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too", "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're", "we've", "were", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "would", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves" ]
    numbers_stopwords = ["1", "2", "3", "4","5","6","7","8","9","10",
                         "one", "two","three","four","five"]
    final_stopwords = stopwords + numbers_stopwords
    # Sentence converted to lowercase-only
    sentence = sentence.lower()
    
    ### START CODE HERE
    words = sentence.split()
    tempWords = []
    for i in words:
        if i not in final_stopwords:
            tempWords.append(i)
            sentence = ' '.join(tempWords)
    
    ### END CODE HERE
    return sentence

In [82]:
len(df)
df['reviews'].values

array(['teacher are punctual but they should also give us the some practical knowledge other than theortical',
       'good',
       'excellent lectures are delivered by teachers and all teachers are very punctual',
       ...,
       'highest recommendations his accent and integrity will keep you awake',
       'great teacher go to class and do hw youll do good',
       'very good professor probably the best in the csci department'],
      dtype=object)

In [83]:
cKomen = []
for i in range(len(df)):
  cKomen.append(remove_stopwords(df['reviews'][i], stopwords_data))

df['reviews'] = cKomen

# Splitting Dataset

We are going to split 80% of the data for training and the rest of the data will become testing data

In [84]:
split = round(len(df)*0.95)
train_reviews = df['reviews'][:split]
train_label = df['sentiment'][:split]
test_reviews = df['reviews'][split:]
test_label = df['sentiment'][split:]

In [85]:
import numpy as np
training_sentences = []
training_labels = []
testing_sentences = []
testing_labels = []
for row in train_reviews:
    training_sentences.append(str(row))
for row in train_label:
    training_labels.append(row)
for row in test_reviews:
    testing_sentences.append(str(row))
for row in test_label:
    testing_labels.append(row)

# Hyper Parameter 

In [86]:
# HyperParameter
vocab_size = 1000
embedding_dim = 32
max_length = 64
trunc_type = 'post'
oov_tok = '<OOV>'
padding_type = 'post'

In [87]:
tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index
word_index

{'<OOV>': 1,
 'class': 2,
 'students': 3,
 'course': 4,
 'teacher': 5,
 'material': 6,
 'professor': 7,
 'lecturer': 8,
 'easy': 9,
 'understand': 10,
 'hard': 11,
 'helpful': 12,
 'dont': 13,
 'help': 14,
 'lectures': 15,
 'learning': 16,
 'questions': 17,
 'teaching': 18,
 'lecture': 19,
 'tests': 20,
 'lecturers': 21,
 'time': 22,
 'lot': 23,
 'math': 24,
 'nice': 25,
 'learn': 26,
 'university': 27,
 'recommend': 28,
 'jokes': 29,
 'makes': 30,
 'study': 31,
 'sometimes': 32,
 'subject': 33,
 'hes': 34,
 'difficult': 35,
 'exam': 36,
 'test': 37,
 'exams': 38,
 'teachers': 39,
 'materials': 40,
 'knowledge': 41,
 'prof': 42,
 'available': 43,
 'knowledgeable': 44,
 'assignments': 45,
 'doesnt': 46,
 'books': 47,
 'lab': 48,
 'excellent': 49,
 'didnt': 50,
 'paper': 51,
 'boring': 52,
 'classes': 53,
 'library': 54,
 'shes': 55,
 'guy': 56,
 'student': 57,
 'bad': 58,
 'extra': 59,
 'homework': 60,
 'answer': 61,
 'taking': 62,
 'book': 63,
 'learned': 64,
 'final': 65,
 'engaging':

# Stemming & Tokenizing

In [88]:
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
ps = PorterStemmer()
 
tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(training_sentences)
words = tokenizer.word_index.keys()

stemmed_words = [ps.stem(word) for word in words]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [89]:
sequences = tokenizer.texts_to_sequences(training_sentences)
padded = pad_sequences(sequences, maxlen=max_length, truncating=trunc_type)
testing_sentences = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sentences, maxlen=max_length)

# Modeling

In [90]:
# Define the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
    # tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(max_length, return_sequences=True)),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

In [91]:
# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 64, 32)            32000     
                                                                 
 bidirectional_2 (Bidirectio  (None, 64, 128)          49664     
 nal)                                                            
                                                                 
 bidirectional_3 (Bidirectio  (None, 64)               41216     
 nal)                                                            
                                                                 
 flatten_4 (Flatten)         (None, 64)                0         
                                                                 
 dense_8 (Dense)             (None, 64)                4160      
                                                                 
 dense_9 (Dense)             (None, 3)                

In [92]:
from tensorflow.keras.utils import to_categorical

training_labels_final = to_categorical(training_labels)
testing_labels_final = to_categorical(testing_labels)

print(training_labels_final)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [93]:
num_epochs = 100
history = model.fit(padded, training_labels_final, epochs=num_epochs, validation_data=(testing_padded, testing_labels_final))

Epoch 1/100
57/57 [==============================] - 20s 177ms/step - loss: 1.0450 - accuracy: 0.4901 - val_loss: 0.9744 - val_accuracy: 0.5579
Epoch 2/100
57/57 [==============================] - 9s 159ms/step - loss: 0.9213 - accuracy: 0.5558 - val_loss: 0.9660 - val_accuracy: 0.5579
Epoch 3/100
57/57 [==============================] - 3s 54ms/step - loss: 0.7083 - accuracy: 0.6790 - val_loss: 0.8693 - val_accuracy: 0.6421
Epoch 4/100
57/57 [==============================] - 2s 28ms/step - loss: 0.6098 - accuracy: 0.7381 - val_loss: 1.0987 - val_accuracy: 0.6421
Epoch 5/100
57/57 [==============================] - 3s 48ms/step - loss: 0.4880 - accuracy: 0.8171 - val_loss: 1.1397 - val_accuracy: 0.6421
Epoch 6/100
57/57 [==============================] - 2s 40ms/step - loss: 0.4063 - accuracy: 0.8525 - val_loss: 1.2712 - val_accuracy: 0.6316
Epoch 7/100
57/57 [==============================] - 1s 23ms/step - loss: 0.3493 - accuracy: 0.8740 - val_loss: 1.2700 - val_accuracy: 0.6632
Epo

# Bert Model

In [94]:
pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [95]:
# import tensorflow as tf
# from transformers import TFBertModel, BertTokenizer

# # Load pre-trained BERT model and tokenizer
# bert_model = TFBertModel.from_pretrained('bert-base-uncased')
# tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# # Example data
# split = round(len(df)*0.8)
# train_reviews = df['reviews'][:split]
# train_label = df['sentiment'][:split]
# test_reviews = df['reviews'][split:]
# test_label = df['sentiment'][split:]

# # Set the maximum sequence length
# max_length = 128

# # Tokenize and encode the training sentences
# train_input_ids = tokenizer.batch_encode_plus(
#     train_reviews.tolist(),
#     padding='max_length',
#     truncation=True,
#     max_length=max_length,
#     return_tensors='tf'
# )

# # Tokenize and encode the testing sentences
# test_input_ids = tokenizer.batch_encode_plus(
#     test_reviews.tolist(),
#     padding='max_length',
#     truncation=True,
#     max_length=max_length,
#     return_tensors='tf'
# )

# # Convert input data to TensorFlow datasets
# train_dataset = tf.data.Dataset.from_tensor_slices((train_input_ids['input_ids'], train_label))
# test_dataset = tf.data.Dataset.from_tensor_slices((test_input_ids['input_ids'], test_label))

# # Define the BERT model architecture
# input_ids = tf.keras.layers.Input(shape=(128,), dtype=tf.int32)
# bert_output = bert_model(input_ids)[0]
# flatten = tf.keras.layers.Flatten()(bert_output)
# dense = tf.keras.layers.Dense(32, activation='relu')(flatten)
# output = tf.keras.layers.Dense(3, activation='softmax')(dense)
# model = tf.keras.models.Model(inputs=input_ids, outputs=output)

# # Compile the model
# model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# # Print the model summary
# model.summary()

# # Train the model
# model.fit(train_dataset.batch(32), epochs=10)

# # Evaluate the model on testing data
# model.evaluate(test_dataset.batch(32))

# # Perform any additional steps such as calculating accuracy or using the predictions for further analysis


In [96]:
import tensorflow as tf
from transformers import TFBertModel, BertTokenizer
from nltk.stem import PorterStemmer

# Load pre-trained BERT model and tokenizer
bert_model = TFBertModel.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Example data
split = round(len(df)*0.8)
train_reviews = df['reviews'][:split]
train_label = df['sentiment'][:split]
test_reviews = df['reviews'][split:]
test_label = df['sentiment'][split:]

# Set the maximum sequence length
max_length = 128

# Create a stemmer
stemmer = PorterStemmer()

# Tokenize, stem, and encode the training sentences
train_input_ids = tokenizer.batch_encode_plus(
    [stemmer.stem(review) for review in train_reviews.tolist()],
    padding='max_length',
    truncation=True,
    max_length=max_length,
    return_tensors='tf'
)

# Tokenize, stem, and encode the testing sentences
test_input_ids = tokenizer.batch_encode_plus(
    [stemmer.stem(review) for review in test_reviews.tolist()],
    padding='max_length',
    truncation=True,
    max_length=max_length,
    return_tensors='tf'
)

# Convert input data to TensorFlow datasets
train_dataset = tf.data.Dataset.from_tensor_slices((train_input_ids['input_ids'], train_label))
test_dataset = tf.data.Dataset.from_tensor_slices((test_input_ids['input_ids'], test_label))

# Define the BERT model architecture
input_ids = tf.keras.layers.Input(shape=(128,), dtype=tf.int32)
bert_output = bert_model(input_ids)[0]
flatten = tf.keras.layers.Flatten()(bert_output)
dense = tf.keras.layers.Dense(32, activation='relu')(flatten)
output = tf.keras.layers.Dense(3, activation='softmax')(dense)
model = tf.keras.models.Model(inputs=input_ids, outputs=output)

# Compile the model
model.compile(optimizer='rmsprop', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Print the model summary
model.summary()

# Train the model
model.fit(train_dataset.batch(32), epochs=10)

# Evaluate the model on testing data
model.evaluate(test_dataset.batch(32))

# Perform any additional steps such as calculating accuracy or using the predictions for further analysis


Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 128)]             0         
                                                                 
 tf_bert_model_3 (TFBertMode  TFBaseModelOutputWithPoo  109482240
 l)                          lingAndCrossAttentions(l            
                             ast_hidden_state=(None,             
                             128, 768),                          
                              pooler_output=(None, 76            
                             8),                                 
                              past_key_values=None, h            
                             idden_states=None, atten            
                             tions=None, cross_attent            
                             ions=None)                          
                                                           

48/48 [==============================] - 93s 770ms/step - loss: 15.3649 - accuracy: 0.4035
Epoch 2/10
48/48 [==============================] - 35s 735ms/step - loss: 1.0923 - accuracy: 0.4606
Epoch 3/10
48/48 [==============================] - 35s 734ms/step - loss: 1.0879 - accuracy: 0.4606
Epoch 4/10
48/48 [==============================] - 36s 741ms/step - loss: 1.0840 - accuracy: 0.4606
Epoch 5/10
48/48 [==============================] - 35s 737ms/step - loss: 1.0806 - accuracy: 0.4606
Epoch 6/10
48/48 [==============================] - 35s 738ms/step - loss: 1.0777 - accuracy: 0.4606
Epoch 7/10
48/48 [==============================] - 36s 741ms/step - loss: 1.0752 - accuracy: 0.4606
Epoch 8/10
48/48 [==============================] - 35s 735ms/step - loss: 1.0731 - accuracy: 0.4606
Epoch 9/10
48/48 [==============================] - 36s 740ms/step - loss: 1.0712 - accuracy: 0.4606
Epoch 10/10
12/12 [==============================] - 7s 263ms/step - loss: 1.0125 - accuracy: 0.6457


[1.012540340423584, 0.6456692814826965]